export type UseCase =
  | 'Gaming' |'Development' |'Privacy' |'Beginner-Friendly' |'Server' |'Education' |'Multimedia' |'Lightweight';

export type Architecture = 'amd64' | 'arm64' | 'x86' | 'riscv';

export type DesktopEnvironment =
  | 'GNOME' |'KDE Plasma' |'XFCE' |'LXDE' |'Cinnamon' |'MATE' |'i3' |'Sway' |'Budgie' |'Pantheon';

export type PackageManager = 'apt' | 'dnf' | 'pacman' | 'zypper' | 'flatpak' | 'nix' | 'emerge';

export type ReleaseModel = 'LTS' | 'Rolling' | 'Fixed' | 'Semi-rolling';

export interface DistroReview {
  id: string;
  author: string;
  avatarInitials: string;
  avatarColor: string;
  rating: number;
  date: string;
  title: string;
  body: string;
  helpful: number;
  verified: boolean;
  useCase: UseCase;
}

export interface DistroVersion {
  id: string;
  version: string;
  codename?: string;
  releaseDate: string;
  supportUntil?: string;
  isLatest: boolean;
  isLTS: boolean;
  downloadUrl: string;
  sizeGb: number;
}

export interface Distro {
  id: string;
  name: string;
  slug: string;
  tagline: string;
  description: string;
  logoColor: string;
  logoInitials: string;
  basedOn: string | null;
  packageManager: PackageManager[];
  desktopEnvironments: DesktopEnvironment[];
  architectures: Architecture[];
  useCases: UseCase[];
  releaseModel: ReleaseModel;
  latestVersion: string;
  releaseDate: string;
  minRamMb: number;
  recommendedRamMb: number;
  minStorageGb: number;
  recommendedStorageGb: number;
  minCpuCores: number;
  communityRating: number;
  reviewCount: number;
  compatibilityScore: number;
  easeOfUse: number;
  hardwareEfficiency: number;
  stabilityScore: number;
  communitySize: number;
  documentationScore: number;
  isPopular: boolean;
  isNew: boolean;
  reviews: DistroReview[];
  versions: DistroVersion[];
}

export const ALL_DISTROS: Distro[] = [
  {
    id: 'distro-001',
    name: 'Ubuntu',
    slug: 'ubuntu',
    tagline: 'The world\'s most popular Linux desktop',
    description:
      'Ubuntu is a Debian-based Linux distribution known for its ease of use, large community, and excellent hardware support. It ships with GNOME by default and offers LTS releases with 5-year support windows, making it the go-to choice for beginners and enterprises alike.',
    logoColor: '#E95420',
    logoInitials: 'UB',
    basedOn: 'Debian',
    packageManager: ['apt', 'flatpak'],
    desktopEnvironments: ['GNOME', 'KDE Plasma', 'XFCE', 'MATE', 'Budgie'],
    architectures: ['amd64', 'arm64'],
    useCases: ['Beginner-Friendly', 'Development', 'Multimedia', 'Education'],
    releaseModel: 'LTS',
    latestVersion: '24.04 LTS',
    releaseDate: 'Apr 25, 2024',
    minRamMb: 2048,
    recommendedRamMb: 4096,
    minStorageGb: 25,
    recommendedStorageGb: 50,
    minCpuCores: 2,
    communityRating: 4.5,
    reviewCount: 2847,
    compatibilityScore: 96,
    easeOfUse: 92,
    hardwareEfficiency: 74,
    stabilityScore: 95,
    communitySize: 98,
    documentationScore: 97,
    isPopular: true,
    isNew: false,
    reviews: [
      {
        id: 'rev-ub-001',
        author: 'Mireille Fontaine',
        avatarInitials: 'MF',
        avatarColor: '#5B6EF7',
        rating: 5,
        date: 'May 18, 2026',
        title: 'Best first Linux experience I\'ve had',
        body: 'Switched from Windows 11 to Ubuntu 24.04 last month. Hardware detection was flawless on my Lenovo ThinkPad E14 — WiFi, Bluetooth, everything worked out of the box. GNOME 46 feels polished and the Software Center makes installing apps trivial. Highly recommend for anyone making the switch.',
        helpful: 142,
        verified: true,
        useCase: 'Beginner-Friendly',
      },
      {
        id: 'rev-ub-002',
        author: 'Rajan Mehta',
        avatarInitials: 'RM',
        avatarColor: '#22D3A5',
        rating: 4,
        date: 'May 10, 2026',
        title: 'Solid dev environment, some snap friction',
        body: 'Ubuntu remains my daily driver for development. Python, Node, Docker all set up in under 30 minutes. My only gripe is snap packages — they load slowly and I end up removing them and using apt/flatpak instead. Still the most practical distro for productive work.',
        helpful: 89,
        verified: true,
        useCase: 'Development',
      },
      {
        id: 'rev-ub-003',
        author: 'Anika Schreiber',
        avatarInitials: 'AS',
        avatarColor: '#E95420',
        rating: 4,
        date: 'Apr 29, 2026',
        title: 'Good multimedia support, heavier than expected',
        body: 'Ubuntu 24.04 handles video editing in Kdenlive without issues. But RAM usage at idle is around 1.4GB which is noticeable on my older 4GB laptop. Switching to Ubuntu MATE helped significantly. Overall a great distro if you have adequate hardware.',
        helpful: 56,
        verified: false,
        useCase: 'Multimedia',
      },
    ],
    versions: [
      {
        id: 'ver-ub-001',
        version: '24.04',
        codename: 'Noble Numbat',
        releaseDate: 'Apr 25, 2024',
        supportUntil: 'Apr 2029',
        isLatest: true,
        isLTS: true,
        downloadUrl: '#',
        sizeGb: 5.1,
      },
      {
        id: 'ver-ub-002',
        version: '22.04',
        codename: 'Jammy Jellyfish',
        releaseDate: 'Apr 21, 2022',
        supportUntil: 'Apr 2027',
        isLatest: false,
        isLTS: true,
        downloadUrl: '#',
        sizeGb: 4.7,
      },
      {
        id: 'ver-ub-003',
        version: '23.10',
        codename: 'Mantic Minotaur',
        releaseDate: 'Oct 12, 2023',
        supportUntil: 'Jul 2024',
        isLatest: false,
        isLTS: false,
        downloadUrl: '#',
        sizeGb: 4.9,
      },
    ],
  },
  {
    id: 'distro-002',
    name: 'Fedora',
    slug: 'fedora',
    tagline: 'Cutting-edge features, upstream-first philosophy',
    description:
      'Fedora is a Red Hat-sponsored distribution that ships the latest upstream software. It uses DNF for package management and defaults to GNOME. Fedora Workstation is ideal for developers who want modern tools without the complexity of Arch.',
    logoColor: '#3C6EB4',
    logoInitials: 'FD',
    basedOn: null,
    packageManager: ['dnf', 'flatpak'],
    desktopEnvironments: ['GNOME', 'KDE Plasma', 'XFCE', 'i3', 'Sway'],
    architectures: ['amd64', 'arm64', 'riscv'],
    useCases: ['Development', 'Privacy', 'Server'],
    releaseModel: 'Fixed',
    latestVersion: '40',
    releaseDate: 'Apr 23, 2024',
    minRamMb: 2048,
    recommendedRamMb: 4096,
    minStorageGb: 20,
    recommendedStorageGb: 40,
    minCpuCores: 2,
    communityRating: 4.4,
    reviewCount: 1203,
    compatibilityScore: 89,
    easeOfUse: 80,
    hardwareEfficiency: 78,
    stabilityScore: 88,
    communitySize: 82,
    documentationScore: 91,
    isPopular: true,
    isNew: false,
    reviews: [
      {
        id: 'rev-fd-001',
        author: 'Carlos Vega',
        avatarInitials: 'CV',
        avatarColor: '#3C6EB4',
        rating: 5,
        date: 'May 20, 2026',
        title: 'Best distro for serious developers',
        body: 'Fedora 40 ships with GCC 14, Python 3.12, and Podman built in. The dev tooling is unmatched. SELinux can be a learning curve but provides serious security. My team standardized on Fedora for all workstations.',
        helpful: 201,
        verified: true,
        useCase: 'Development',
      },
      {
        id: 'rev-fd-002',
        author: 'Priya Nair',
        avatarInitials: 'PN',
        avatarColor: '#22D3A5',
        rating: 4,
        date: 'May 5, 2026',
        title: 'Great but short release cycle is annoying',
        body: 'Fedora keeps software fresh — GNOME 46 landed here first. However the 13-month lifecycle means you\'re upgrading frequently. The dnf system upgrade process is reliable though. Would recommend to developers comfortable with occasional system updates.',
        helpful: 77,
        verified: true,
        useCase: 'Development',
      },
    ],
    versions: [
      {
        id: 'ver-fd-001',
        version: '40',
        releaseDate: 'Apr 23, 2024',
        supportUntil: 'May 2025',
        isLatest: true,
        isLTS: false,
        downloadUrl: '#',
        sizeGb: 2.1,
      },
      {
        id: 'ver-fd-002',
        version: '39',
        releaseDate: 'Nov 7, 2023',
        supportUntil: 'Nov 2024',
        isLatest: false,
        isLTS: false,
        downloadUrl: '#',
        sizeGb: 2.0,
      },
    ],
  },
  {
    id: 'distro-003',
    name: 'Arch Linux',
    slug: 'arch',
    tagline: 'A simple, lightweight distribution for experienced users',
    description:
      'Arch Linux is a rolling-release distribution following the KISS principle. Users build their system from the ground up, gaining deep understanding of Linux internals. Pacman and the AUR give access to virtually any software package.',
    logoColor: '#1793D1',
    logoInitials: 'AR',
    basedOn: null,
    packageManager: ['pacman'],
    desktopEnvironments: ['KDE Plasma', 'GNOME', 'i3', 'Sway', 'XFCE'],
    architectures: ['amd64', 'arm64'],
    useCases: ['Development', 'Privacy', 'Gaming'],
    releaseModel: 'Rolling',
    latestVersion: '2024.05.01',
    releaseDate: 'May 1, 2024',
    minRamMb: 512,
    recommendedRamMb: 2048,
    minStorageGb: 8,
    recommendedStorageGb: 20,
    minCpuCores: 1,
    communityRating: 4.7,
    reviewCount: 984,
    compatibilityScore: 72,
    easeOfUse: 28,
    hardwareEfficiency: 98,
    stabilityScore: 78,
    communitySize: 90,
    documentationScore: 99,
    isPopular: true,
    isNew: false,
    reviews: [
      {
        id: 'rev-ar-001',
        author: 'Søren Lindqvist',
        avatarInitials: 'SL',
        avatarColor: '#1793D1',
        rating: 5,
        date: 'May 22, 2026',
        title: 'I use Arch, btw — and for good reason',
        body: 'The Arch Wiki alone is worth the price of admission. Rolling release means I\'m always on the latest kernel and software. After the initial setup effort, my system runs exactly how I want it — nothing more, nothing less. 512MB RAM idle. Unbeatable.',
        helpful: 312,
        verified: true,
        useCase: 'Development',
      },
    ],
    versions: [
      {
        id: 'ver-ar-001',
        version: '2024.05.01',
        releaseDate: 'May 1, 2024',
        isLatest: true,
        isLTS: false,
        downloadUrl: '#',
        sizeGb: 0.8,
      },
    ],
  },
  {
    id: 'distro-004',
    name: 'Linux Mint',
    slug: 'mint',
    tagline: 'Familiar, comfortable, and easy to use',
    description:
      'Linux Mint is built on Ubuntu and designed to provide a comfortable, familiar desktop experience for users transitioning from Windows. Cinnamon desktop, excellent multimedia support out of the box, and a conservative update policy make it one of the most loved beginner distros.',
    logoColor: '#87CF3E',
    logoInitials: 'LM',
    basedOn: 'Ubuntu',
    packageManager: ['apt', 'flatpak'],
    desktopEnvironments: ['Cinnamon', 'MATE', 'XFCE'],
    architectures: ['amd64'],
    useCases: ['Beginner-Friendly', 'Multimedia', 'Education'],
    releaseModel: 'LTS',
    latestVersion: '21.3',
    releaseDate: 'Jan 12, 2024',
    minRamMb: 2048,
    recommendedRamMb: 4096,
    minStorageGb: 20,
    recommendedStorageGb: 40,
    minCpuCores: 2,
    communityRating: 4.6,
    reviewCount: 2104,
    compatibilityScore: 93,
    easeOfUse: 96,
    hardwareEfficiency: 76,
    stabilityScore: 94,
    communitySize: 88,
    documentationScore: 88,
    isPopular: true,
    isNew: false,
    reviews: [
      {
        id: 'rev-lm-001',
        author: 'Dorothy Okafor',
        avatarInitials: 'DO',
        avatarColor: '#87CF3E',
        rating: 5,
        date: 'May 15, 2026',
        title: 'My 65-year-old mother uses this daily',
        body: 'I set up Linux Mint Cinnamon on my mother\'s old HP laptop. She was comfortable in under an hour. The Cinnamon desktop feels like Windows 7 — familiar enough that she never needed to call me for help. Firefox, LibreOffice, VLC all pre-installed. Perfect.',
        helpful: 445,
        verified: true,
        useCase: 'Beginner-Friendly',
      },
    ],
    versions: [
      {
        id: 'ver-lm-001',
        version: '21.3',
        codename: 'Virginia',
        releaseDate: 'Jan 12, 2024',
        supportUntil: 'Apr 2027',
        isLatest: true,
        isLTS: true,
        downloadUrl: '#',
        sizeGb: 2.7,
      },
    ],
  },
  {
    id: 'distro-005',
    name: 'Tails',
    slug: 'tails',
    tagline: 'Privacy and anonymity by design',
    description:
      'Tails is a live operating system focused on privacy and security. It routes all internet traffic through Tor, leaves no trace on the host machine, and includes tools for secure communication and encryption. Designed for journalists, activists, and privacy-conscious users.',
    logoColor: '#56347C',
    logoInitials: 'TL',
    basedOn: 'Debian',
    packageManager: ['apt'],
    desktopEnvironments: ['GNOME'],
    architectures: ['amd64'],
    useCases: ['Privacy'],
    releaseModel: 'Fixed',
    latestVersion: '6.3',
    releaseDate: 'May 14, 2024',
    minRamMb: 2048,
    recommendedRamMb: 4096,
    minStorageGb: 0,
    recommendedStorageGb: 8,
    minCpuCores: 2,
    communityRating: 4.3,
    reviewCount: 567,
    compatibilityScore: 65,
    easeOfUse: 55,
    hardwareEfficiency: 71,
    stabilityScore: 91,
    communitySize: 60,
    documentationScore: 92,
    isPopular: false,
    isNew: false,
    reviews: [
      {
        id: 'rev-tl-001',
        author: 'Anonymous User',
        avatarInitials: 'AU',
        avatarColor: '#56347C',
        rating: 5,
        date: 'Apr 20, 2026',
        title: 'Essential tool for sensitive work',
        body: 'For investigative journalism, Tails is irreplaceable. Boot from USB, do your work, shut down — no traces. Tor integration is seamless. Persistence storage feature lets me keep encrypted documents across sessions. The security model is sound and regularly audited.',
        helpful: 189,
        verified: false,
        useCase: 'Privacy',
      },
    ],
    versions: [
      {
        id: 'ver-tl-001',
        version: '6.3',
        releaseDate: 'May 14, 2024',
        isLatest: true,
        isLTS: false,
        downloadUrl: '#',
        sizeGb: 1.3,
      },
    ],
  },
  {
    id: 'distro-006',
    name: 'Pop!_OS',
    slug: 'popos',
    tagline: 'Built for creators and developers by System76',
    description:
      'Pop!_OS is System76\'s Ubuntu-based distribution with a custom COSMIC desktop environment (transitioning to Rust-based COSMIC). Excellent NVIDIA driver support out of the box, automatic tiling window management, and a curated app store make it a top pick for developers and content creators.',
    logoColor: '#48B9C7',
    logoInitials: 'PO',
    basedOn: 'Ubuntu',
    packageManager: ['apt', 'flatpak'],
    desktopEnvironments: ['GNOME', 'KDE Plasma'],
    architectures: ['amd64'],
    useCases: ['Development', 'Gaming', 'Multimedia'],
    releaseModel: 'LTS',
    latestVersion: '22.04 LTS',
    releaseDate: 'Apr 25, 2022',
    minRamMb: 4096,
    recommendedRamMb: 8192,
    minStorageGb: 20,
    recommendedStorageGb: 50,
    minCpuCores: 2,
    communityRating: 4.5,
    reviewCount: 1456,
    compatibilityScore: 91,
    easeOfUse: 85,
    hardwareEfficiency: 72,
    stabilityScore: 90,
    communitySize: 76,
    documentationScore: 84,
    isPopular: true,
    isNew: false,
    reviews: [
      {
        id: 'rev-po-001',
        author: 'James Okonkwo',
        avatarInitials: 'JO',
        avatarColor: '#48B9C7',
        rating: 5,
        date: 'May 21, 2026',
        title: 'NVIDIA works perfectly, no tweaks needed',
        body: 'Switched from Ubuntu after spending 2 hours fighting NVIDIA drivers. Pop!_OS asked me at install if I have NVIDIA — selected yes — and everything worked. CUDA, games via Steam Proton, dual-monitor setup. This is what Linux gaming should feel like.',
        helpful: 334,
        verified: true,
        useCase: 'Gaming',
      },
    ],
    versions: [
      {
        id: 'ver-po-001',
        version: '22.04',
        codename: 'Jammy',
        releaseDate: 'Apr 25, 2022',
        supportUntil: 'Apr 2027',
        isLatest: true,
        isLTS: true,
        downloadUrl: '#',
        sizeGb: 2.8,
      },
    ],
  },
  {
    id: 'distro-007',
    name: 'openSUSE Tumbleweed',
    slug: 'opensuse-tumbleweed',
    tagline: 'Rolling release with enterprise-grade tooling',
    description:
      'openSUSE Tumbleweed is a rolling-release distribution backed by SUSE. It features YaST — a powerful system configuration tool — and the zypper package manager. Tumbleweed gets the latest kernel and software while maintaining stability through automated openQA testing.',
    logoColor: '#73BA25',
    logoInitials: 'OT',
    basedOn: null,
    packageManager: ['zypper', 'flatpak'],
    desktopEnvironments: ['KDE Plasma', 'GNOME', 'XFCE'],
    architectures: ['amd64', 'arm64', 'x86'],
    useCases: ['Development', 'Server', 'Privacy'],
    releaseModel: 'Rolling',
    latestVersion: '20240520',
    releaseDate: 'May 20, 2024',
    minRamMb: 2048,
    recommendedRamMb: 4096,
    minStorageGb: 20,
    recommendedStorageGb: 40,
    minCpuCores: 2,
    communityRating: 4.2,
    reviewCount: 445,
    compatibilityScore: 84,
    easeOfUse: 68,
    hardwareEfficiency: 82,
    stabilityScore: 87,
    communitySize: 70,
    documentationScore: 86,
    isPopular: false,
    isNew: false,
    reviews: [],
    versions: [
      {
        id: 'ver-ot-001',
        version: '20240520',
        releaseDate: 'May 20, 2024',
        isLatest: true,
        isLTS: false,
        downloadUrl: '#',
        sizeGb: 4.2,
      },
    ],
  },
  {
    id: 'distro-008',
    name: 'Debian',
    slug: 'debian',
    tagline: 'The universal operating system — rock-solid stability',
    description:
      'Debian is one of the oldest and most influential Linux distributions, known for extreme stability and a massive package repository. It forms the base of Ubuntu, Mint, and hundreds of other distros. Debian Stable is the choice for servers and users who prioritize reliability over cutting-edge software.',
    logoColor: '#D70751',
    logoInitials: 'DB',
    basedOn: null,
    packageManager: ['apt'],
    desktopEnvironments: ['GNOME', 'KDE Plasma', 'XFCE', 'LXDE', 'MATE'],
    architectures: ['amd64', 'arm64', 'x86', 'riscv'],
    useCases: ['Server', 'Development', 'Privacy', 'Education'],
    releaseModel: 'Fixed',
    latestVersion: '12.5',
    releaseDate: 'Feb 10, 2024',
    minRamMb: 512,
    recommendedRamMb: 2048,
    minStorageGb: 10,
    recommendedStorageGb: 20,
    minCpuCores: 1,
    communityRating: 4.4,
    reviewCount: 1678,
    compatibilityScore: 82,
    easeOfUse: 62,
    hardwareEfficiency: 94,
    stabilityScore: 99,
    communitySize: 92,
    documentationScore: 95,
    isPopular: true,
    isNew: false,
    reviews: [],
    versions: [
      {
        id: 'ver-db-001',
        version: '12.5',
        codename: 'Bookworm',
        releaseDate: 'Feb 10, 2024',
        supportUntil: 'Jun 2028',
        isLatest: true,
        isLTS: true,
        downloadUrl: '#',
        sizeGb: 3.9,
      },
    ],
  },
  {
    id: 'distro-009',
    name: 'NixOS',
    slug: 'nixos',
    tagline: 'Declarative, reproducible system configuration',
    description:
      'NixOS is a Linux distribution built on the Nix package manager. System configuration is declared in a single file, enabling fully reproducible builds and atomic rollbacks. Popular among developers and DevOps engineers who value infrastructure-as-code principles for their workstations.',
    logoColor: '#7EBAE4',
    logoInitials: 'NX',
    basedOn: null,
    packageManager: ['nix'],
    desktopEnvironments: ['KDE Plasma', 'GNOME', 'i3', 'Sway'],
    architectures: ['amd64', 'arm64'],
    useCases: ['Development', 'Server', 'Privacy'],
    releaseModel: 'Rolling',
    latestVersion: '24.05',
    releaseDate: 'May 31, 2024',
    minRamMb: 2048,
    recommendedRamMb: 4096,
    minStorageGb: 20,
    recommendedStorageGb: 50,
    minCpuCores: 2,
    communityRating: 4.6,
    reviewCount: 389,
    compatibilityScore: 70,
    easeOfUse: 22,
    hardwareEfficiency: 86,
    stabilityScore: 96,
    communitySize: 65,
    documentationScore: 88,
    isPopular: false,
    isNew: true,
    reviews: [],
    versions: [
      {
        id: 'ver-nx-001',
        version: '24.05',
        codename: 'Uakari',
        releaseDate: 'May 31, 2024',
        isLatest: true,
        isLTS: false,
        downloadUrl: '#',
        sizeGb: 1.2,
      },
    ],
  },
  {
    id: 'distro-010',
    name: 'Manjaro',
    slug: 'manjaro',
    tagline: 'Arch-based with beginner-friendly polish',
    description:
      'Manjaro bridges the gap between Arch Linux\'s power and a beginner-friendly experience. It ships with hardware detection, a graphical installer, and a curated selection of pre-installed software. Packages arrive a week after Arch, providing a stability buffer on the rolling release model.',
    logoColor: '#35BF5C',
    logoInitials: 'MJ',
    basedOn: 'Arch Linux',
    packageManager: ['pacman', 'flatpak'],
    desktopEnvironments: ['KDE Plasma', 'XFCE', 'GNOME', 'i3'],
    architectures: ['amd64', 'arm64'],
    useCases: ['Gaming', 'Development', 'Beginner-Friendly'],
    releaseModel: 'Rolling',
    latestVersion: '24.0',
    releaseDate: 'Apr 30, 2024',
    minRamMb: 2048,
    recommendedRamMb: 4096,
    minStorageGb: 30,
    recommendedStorageGb: 50,
    minCpuCores: 2,
    communityRating: 4.3,
    reviewCount: 1847,
    compatibilityScore: 87,
    easeOfUse: 79,
    hardwareEfficiency: 84,
    stabilityScore: 82,
    communitySize: 85,
    documentationScore: 82,
    isPopular: true,
    isNew: false,
    reviews: [],
    versions: [
      {
        id: 'ver-mj-001',
        version: '24.0',
        codename: 'Wynsdey',
        releaseDate: 'Apr 30, 2024',
        isLatest: true,
        isLTS: false,
        downloadUrl: '#',
        sizeGb: 3.4,
      },
    ],
  },
  {
    id: 'distro-011',
    name: 'Kali Linux',
    slug: 'kali',
    tagline: 'Penetration testing and security research platform',
    description:
      'Kali Linux is a Debian-based distribution specifically designed for penetration testing, digital forensics, and security research. It ships with 600+ security tools pre-installed including Metasploit, Wireshark, and Burp Suite. Not recommended as a daily driver.',
    logoColor: '#367BF0',
    logoInitials: 'KL',
    basedOn: 'Debian',
    packageManager: ['apt'],
    desktopEnvironments: ['XFCE', 'GNOME', 'KDE Plasma'],
    architectures: ['amd64', 'arm64', 'x86'],
    useCases: ['Privacy', 'Development'],
    releaseModel: 'Rolling',
    latestVersion: '2024.2',
    releaseDate: 'May 22, 2024',
    minRamMb: 2048,
    recommendedRamMb: 4096,
    minStorageGb: 20,
    recommendedStorageGb: 50,
    minCpuCores: 2,
    communityRating: 4.1,
    reviewCount: 923,
    compatibilityScore: 76,
    easeOfUse: 40,
    hardwareEfficiency: 77,
    stabilityScore: 81,
    communitySize: 78,
    documentationScore: 89,
    isPopular: false,
    isNew: false,
    reviews: [],
    versions: [
      {
        id: 'ver-kl-001',
        version: '2024.2',
        releaseDate: 'May 22, 2024',
        isLatest: true,
        isLTS: false,
        downloadUrl: '#',
        sizeGb: 3.9,
      },
    ],
  },
  {
    id: 'distro-012',
    name: 'Lubuntu',
    slug: 'lubuntu',
    tagline: 'Ultra-lightweight Ubuntu for old hardware',
    description:
      'Lubuntu is the official Ubuntu flavor using the LXQt desktop environment. It is designed to be extremely fast and energy-efficient, making it the best choice for older computers with limited RAM. Despite being lightweight, it provides a full desktop experience and access to Ubuntu\'s software repositories.',
    logoColor: '#0068C8',
    logoInitials: 'LU',
    basedOn: 'Ubuntu',
    packageManager: ['apt', 'flatpak'],
    desktopEnvironments: ['LXDE'],
    architectures: ['amd64', 'x86'],
    useCases: ['Lightweight', 'Beginner-Friendly', 'Education'],
    releaseModel: 'LTS',
    latestVersion: '24.04 LTS',
    releaseDate: 'Apr 25, 2024',
    minRamMb: 512,
    recommendedRamMb: 1024,
    minStorageGb: 8,
    recommendedStorageGb: 20,
    minCpuCores: 1,
    communityRating: 4.2,
    reviewCount: 678,
    compatibilityScore: 88,
    easeOfUse: 82,
    hardwareEfficiency: 97,
    stabilityScore: 91,
    communitySize: 72,
    documentationScore: 85,
    isPopular: false,
    isNew: false,
    reviews: [],
    versions: [
      {
        id: 'ver-lu-001',
        version: '24.04',
        codename: 'Noble Numbat',
        releaseDate: 'Apr 25, 2024',
        supportUntil: 'Apr 2027',
        isLatest: true,
        isLTS: true,
        downloadUrl: '#',
        sizeGb: 2.1,
      },
    ],
  },
];

export const USE_CASE_CONFIG: Record<UseCase, { color: string; bg: string; label: string }> = {
  Gaming: { color: 'text-purple-700', bg: 'bg-purple-100', label: 'Gaming' },
  Development: { color: 'text-blue-700', bg: 'bg-blue-100', label: 'Development' },
  Privacy: { color: 'text-slate-700', bg: 'bg-slate-100', label: 'Privacy' },
  'Beginner-Friendly': { color: 'text-green-700', bg: 'bg-green-100', label: 'Beginner' },
  Server: { color: 'text-orange-700', bg: 'bg-orange-100', label: 'Server' },
  Education: { color: 'text-yellow-700', bg: 'bg-yellow-100', label: 'Education' },
  Multimedia: { color: 'text-pink-700', bg: 'bg-pink-100', label: 'Multimedia' },
  Lightweight: { color: 'text-teal-700', bg: 'bg-teal-100', label: 'Lightweight' },
};